services:
  nginx:
    container_name: app_web
    restart: on-failure
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    depends_on:
      - api
  api:
    container_name: app_api
    build: ./api   
    depends_on:
      - db     
    volumes:
      - ./api:/api
    command: sh -c "python manage.py migrate --no-input && gunicorn core_api.wsgi:application --bind 0.0.0.0:8000"
  db:
    container_name: app_db
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: coredb
      MYSQL_USER: admin
      MYSQL_PASSWORD: Markuss1!*
      MYSQL_ROOT_PASSWORD: MARKUSS1234
    volumes:
      - mysql-data:/var/lib/mysql



volumes:
  mysql-data:
