# Generated by Django 4.2.7 on 2024-01-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTanque',
            fields=[
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('FECHAMOV', models.DateField(auto_now_add=True)),
                ('Unidad_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40)),
                ('kilometraje_act', models.FloatField()),
                ('ultima_modif', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('FECHAMOV', models.DateField(auto_now_add=True)),
                ('Empresa_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('Razon_social', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('FECHAMOV', models.DateField(auto_now_add=True)),
                ('Estacion_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('is_WHOLESALE', models.BooleanField()),
                ('is_SUPER', models.BooleanField()),
                ('Estacion_Nombre', models.CharField(max_length=20)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('FECHAMOV', models.DateField(auto_now_add=True)),
                ('Producto_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('FECHAMOV', models.DateField(auto_now_add=True)),
                ('Venta_id', models.AutoField(primary_key=True, serialize=False)),
                ('volumen', models.FloatField()),
                ('Fecha', models.DateField()),
                ('Estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.estacion')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteDinero',
            fields=[
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('FECHAMOV', models.DateField(auto_now_add=True)),
                ('Reporte_dinero_id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('PANAMERICANO', models.FloatField()),
                ('SUPER', models.FloatField()),
                ('Estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.estacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PruebaBombas',
            fields=[
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('FECHAMOV', models.DateField(auto_now_add=True)),
                ('Prueba_id', models.AutoField(primary_key=True, serialize=False)),
                ('volumen', models.FloatField()),
                ('Fecha', models.DateField()),
                ('Estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.estacion')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MOVMEDTANQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('FECHAMOV', models.DateField(auto_now_add=True)),
                ('FECHA', models.DateField()),
                ('TANQUE_ID', models.CharField(max_length=2)),
                ('LTSETT', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CMSREG', models.DecimalField(decimal_places=2, max_digits=15)),
                ('LTSREG', models.DecimalField(decimal_places=2, max_digits=15)),
                ('HORAMOV', models.TimeField(auto_now_add=True)),
                ('ESTACION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.estacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='movmedagualuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('FECHAMOV', models.DateField(auto_now_add=True)),
                ('FECHA', models.DateField()),
                ('MEDAguaAnt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MEDAguaAct', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ConsumoAgua', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MEDLuzAnt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MEDLuzAct', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ConsumoLuz', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ESTACION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.estacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioCombustibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('FECHAMOV', models.DateField(auto_now_add=True)),
                ('FECHA', models.DateField()),
                ('FISICA', models.DecimalField(decimal_places=2, max_digits=15)),
                ('EXISTENCIA_CONTABLE', models.DecimalField(decimal_places=2, max_digits=15)),
                ('LTSVENTA', models.DecimalField(decimal_places=2, max_digits=15)),
                ('LTSMOV', models.DecimalField(decimal_places=2, max_digits=15)),
                ('VOLUMEN', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DIFERENCIA', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DIFERENCIA_ACUMULADA', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ESTACION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.estacion')),
                ('PRODUCTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dispensario',
            fields=[
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('FECHAMOV', models.DateField(auto_now_add=True)),
                ('Dispensario_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('NumeroTanque', models.CharField(max_length=2)),
                ('codigo', models.CharField(max_length=5)),
                ('Nombre', models.CharField(max_length=40)),
                ('Estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.estacion')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('FECHAMOV', models.DateField(auto_now_add=True)),
                ('compra_id', models.AutoField(primary_key=True, serialize=False)),
                ('volumen', models.FloatField()),
                ('Fecha', models.DateField()),
                ('Estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.estacion')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CATTABCUB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TANQUE_ID', models.CharField(max_length=2)),
                ('CMS', models.CharField(max_length=4)),
                ('LITROS', models.DecimalField(decimal_places=2, max_digits=15)),
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('ESTACION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='CargaAutoTanques',
            fields=[
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('FECHAMOV', models.DateField(auto_now_add=True)),
                ('Carga_id', models.AutoField(primary_key=True, serialize=False)),
                ('volumen_Carga', models.FloatField()),
                ('kilometraje', models.FloatField()),
                ('Fecha', models.DateField()),
                ('Estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.estacion')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.producto')),
                ('Unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.autotanque')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='autotanque',
            name='Empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.empresa'),
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('FECHAMOV', models.DateField(auto_now_add=True)),
                ('tanque_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Numero', models.CharField(max_length=20)),
                ('Vertical', models.CharField(max_length=1)),
                ('Capacidad', models.FloatField(default=0)),
                ('Altura', models.FloatField(default=0)),
                ('Diametro', models.FloatField(default=0)),
                ('Existencia', models.FloatField()),
                ('Usuario_ultmodif', models.CharField(max_length=20)),
                ('Estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.estacion')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.producto')),
            ],
            options={
                'unique_together': {('tanque_id', 'Estacion')},
            },
        ),
    ]
