# Generated by Django 4.2.7 on 2024-01-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_stationdata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movmedagualuz',
        ),
    ]
