# Generated by Django 4.2.7 on 2024-01-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_stationdata', '0002_delete_movmedagualuz'),
    ]

    operations = [
        migrations.CreateModel(
            name='movmedagualuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STATUS', models.CharField(default='A', max_length=1)),
                ('FECHAMOV', models.DateField(auto_now_add=True)),
                ('FECHA', models.DateField()),
                ('MEDAguaAnt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MEDAguaAct', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ConsumoAgua', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MEDLuzAnt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('MEDLuzAct', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ConsumoLuz', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ESTACION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_stationdata.estacion')),
                ('EXAMPLE', models.DecimalField(decimal_places=2, max_digits=15)),

            ],
            options={
                'abstract': False,
            },
        ),
    ]
